// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inntygdyzkycomafwgup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubnR5Z2R5emt5Y29tYWZ3Z3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODQwMDIsImV4cCI6MjA2MDg2MDAwMn0.4FqLV575tTJWQm9aC5eUjnZGkT66j_zrE7Npp9HwZiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);